export { AnimatedSection, AnimatedChild } from './AnimatedSection';
export { VideoBackground } from './VideoBackground';
export { Navigation } from './Navigation';
export { Hero } from './Hero';
export { Philosophy } from './Philosophy';
export { SystemLayers } from './SystemLayers';
export { Trust } from './Trust';
export { Capabilities } from './Capabilities';
export { Industries } from './Industries';
export { Finale } from './Finale';
export { Footer } from './Footer';
